//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { environment } from '../../environments/environment';
import { Observable } from 'rxjs';
@Injectable({ providedIn: 'root' })
 export class ProjectsApiService
{
	constructor (private http: HttpClient) { } 
	public getAllPublished() : any
	{
		return null;
	}
	public getAll() : any
	{
		return null;
	}
	public getAllByUser() : any
	{
		return null;
	}
	public getById(id: string) : any
	{
		return null;
	}
	public create(command: any) : any
	{
		return null;
	}
	public supportProject(command: any) : any
	{
		return null;
	}
	public publishProject(command: any) : any
	{
		return null;
	}
	public delete(id: string) : any
	{
		return null;
	}
	public update(id: string, command: any) : any
	{
		return null;
	}
}
export interface IProjectDto
{
}
export interface IProjectWithTiersDto
{
}
export interface IPublishedProjectDto
{
}
export interface ITierDto
{
}
