//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface ITierDto
{
	id: string;
	tierName: string;
	requiredMoney: number;
	isReached: boolean;
	benefit: string;
}
