//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface IProjectDto
{
	id: string;
	title: string;
	description: string;
	titleImage: string;
	investedMoney: number;
	requiredMoney: number;
	status: string;
	lastDay: Date;
	creatorName: string;
	supporters: string[];
}
