//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { ITierDto } from '../Tier/ITierDto';

export interface IProjectWithTiersDto
{
	id: string;
	title: string;
	description: string;
	imageUrl: string;
	status: string;
	investedMoney: number;
	requiredMoney: number;
	lastDay: Date;
	creatorName: string;
	tiers: ITierDto[];
}
