//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface IRegisterUserCommand
{
	userName: string;
	fullName: string;
	description: string;
	emailAddress: string;
	password: string;
	adminKey: string;
	role: string;
}
